[versions]
analytics = "7.3.0"
kotlin = "2.0.21"
compose = "1.7.1"
agp = "8.5.2"
realm = "3.0.0"
androidx-activityCompose = "1.9.3"
androidx-core-ktx = "1.15.0"
voyagerScreenmodel = "1.0.1"
yandex-ads = "7.7.0"
work-manager = "2.10.0"
voyager = "1.1.0-beta03"
kotlinx-datetime = "0.6.1"
material3 = "1.4.0"

[libraries]
analytics = { module = "io.appmetrica.analytics:analytics", version.ref = "analytics" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
mobileads-ios = { module = "com.yandex.android:mobileads-ios", version.ref = "yandex-ads" }
realm-library-base = { module = "io.realm.kotlin:library-base", version.ref = "realm" }

# Библиотеки для устранения Unresolved reference
voyager-screenmodel = { module = "cafe.adriel.voyager:voyager-screenmodel", version.ref = "voyagerScreenmodel" }
yandex-mobileads = { module = "com.yandex.android:mobileads", version.ref = "yandex-ads" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work-manager" }
voyager-navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyager" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
realm-kotlin = { id = "io.realm.kotlin", version.ref = "realm" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }